name: 'publish-tauri-application'

on:
  pull_request:
    branches: [ "**" ] 
  push:
    branches: [ "main" ]

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.3'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install tauri
        run: cargo install tauri-cli --version "^2.0.0" --locked

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: yarn install 

      - name: app version 
        id: versioner
        run: |
          echo "APP_VERSION=$(grep "^version" ./src-tauri/Cargo.toml | cut -d '"' -f 2)" >> "$GITHUB_OUTPUT"

      - name: build
        run: |
          cargo tauri build -- ${{ matrix.args }}

      - name: Upload deb
        if: matrix.platform == 'ubuntu-22.04' && success()
        uses: actions/upload-artifact@v3
        with:
          name: KavkaMessenger.deb
          path: src-tauri/target/release/bundle/deb/Kavka Messenger_${{steps.versioner.outputs.APP_VERSION}}_.amd64.deb

      - name: Upload rpm
        if: matrix.platform == 'ubuntu-22.04' && success()
        uses: actions/upload-artifact@v3
        with:
          name: KavkaMessenger.rpm
          path: src-tauri/target/release/bundle/rpm/Kavka Messenger-${{steps.versioner.outputs.APP_VERSION}}-1.x86_64.rpm

      - name: Upload exe
        if: matrix.platform == 'windows-latest' && success()
        uses: actions/upload-artifact@v3
        with:
          name: KavkaMessenger.exe
          path: src-tauri/target/release/bundle/msi/Kavka Messenger-${{steps.versioner.outputs.APP_VERSION}}_x64_en-US.msi

      - name: Upload AppImage
        if: matrix.platform == 'windows-latest' && success()
        uses: actions/upload-artifact@v3
        with:
          name: KavkaMessenger.AppImage
          path: src-tauri/target/release/bundle/appimage/Kavka Messenger_${{steps.versioner.outputs.APP_VERSION}}_amd64.AppImage